/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GymFrame.java
 *
 * Created on Oct 11, 2017, 2:52:06 PM
 */
package gymsym;

import java.awt.Color;
import java.awt.Image;
import java.awt.List;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPasswordField;

/**
 *
 * @author user
 */
public class GymFrame extends javax.swing.JFrame {

    /** Creates new form GymFrame */
    
        JPasswordField p1 = new JPasswordField("password",20);
        static FileWriter fw;
        double base_price = 0.0;
        double price;
        //ImageIcon cards1 = new ImageIcon("./src/lib/card-icons.png");
        //Image scaleImage = cards1.getImage().getScaledInstance(10,10,Image.SCALE_DEFAULT);
        
    public GymFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame_Register = new javax.swing.JFrame();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        REG_Name = new javax.swing.JTextField();
        REG_Surname = new javax.swing.JTextField();
        REG_Username = new javax.swing.JTextField();
        REG_Password = new javax.swing.JPasswordField();
        REG_ConfirmPass = new javax.swing.JPasswordField();
        REG_Email = new javax.swing.JTextField();
        BUT_RegConfirm = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Registration_Message = new javax.swing.JLabel();
        BUT_PriceWindow = new javax.swing.JButton();
        Register_Confirm = new javax.swing.JDialog();
        REG_windowConfirm = new javax.swing.JLabel();
        BUT_OK = new javax.swing.JButton();
        FRA_Admin = new javax.swing.JFrame();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        FRA_PriceWindow = new javax.swing.JFrame();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SP_Total = new javax.swing.JSpinner();
        LB_Time = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        LB_TotalPrice = new javax.swing.JLabel();
        BUT_Pay = new javax.swing.JButton();
        syndromi = new javax.swing.ButtonGroup();
        FRA_Pay = new javax.swing.JFrame();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        BUT_FullBuy = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        GymSum = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        TF_Username = new javax.swing.JTextField();
        BUT_Login = new javax.swing.JButton();
        BUT_Cancel = new javax.swing.JButton();
        BUT_FPass = new javax.swing.JButton();
        LB_Message = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BUT_Register = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        jFrame_Register.setAlwaysOnTop(true);
        jFrame_Register.setMaximumSize(new java.awt.Dimension(553, 440));
        jFrame_Register.setMinimumSize(new java.awt.Dimension(553, 440));
        jFrame_Register.setPreferredSize(new java.awt.Dimension(553, 440));
        jFrame_Register.setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Registration");

        jLabel2.setText("Όνομα:");

        jLabel3.setText("Επίθετο:");

        jLabel4.setText("Username:");

        jLabel5.setText("Password:");

        jLabel6.setText("Confirm Password:");

        jLabel7.setText("Email:");

        REG_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REG_NameActionPerformed(evt);
            }
        });

        REG_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REG_EmailActionPerformed(evt);
            }
        });

        BUT_RegConfirm.setText("Register");
        BUT_RegConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUT_RegConfirmActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BUT_PriceWindow.setText("Υπολογισμός Κόστους");
        BUT_PriceWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUT_PriceWindowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame_RegisterLayout = new javax.swing.GroupLayout(jFrame_Register.getContentPane());
        jFrame_Register.getContentPane().setLayout(jFrame_RegisterLayout);
        jFrame_RegisterLayout.setHorizontalGroup(
            jFrame_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jFrame_RegisterLayout.createSequentialGroup()
                .addGroup(jFrame_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jFrame_RegisterLayout.createSequentialGroup()
                        .addGroup(jFrame_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame_RegisterLayout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame_RegisterLayout.createSequentialGroup()
                                .addContainerGap(86, Short.MAX_VALUE)
                                .addGroup(jFrame_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(82, 82, 82)
                                .addGroup(jFrame_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(REG_Name)
                                    .addComponent(REG_Surname)
                                    .addComponent(REG_Username)
                                    .addComponent(REG_Password)
                                    .addComponent(REG_ConfirmPass)
                                    .addComponent(REG_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))))
                        .addGap(15, 15, 15))
                    .addGroup(jFrame_RegisterLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(BUT_PriceWindow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Registration_Message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(BUT_RegConfirm)
                        .addGap(18, 18, 18)))
                .addComponent(jButton2)
                .addContainerGap())
        );
        jFrame_RegisterLayout.setVerticalGroup(
            jFrame_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_RegisterLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jFrame_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(REG_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(REG_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(REG_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(REG_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(REG_ConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jFrame_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(REG_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(43, 43, 43)
                .addGroup(jFrame_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Registration_Message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jFrame_RegisterLayout.createSequentialGroup()
                        .addGroup(jFrame_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BUT_RegConfirm)
                                .addComponent(jButton2))
                            .addComponent(BUT_PriceWindow))
                        .addGap(0, 89, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Register_Confirm.setAlwaysOnTop(true);
        Register_Confirm.setMaximumSize(new java.awt.Dimension(412, 170));
        Register_Confirm.setMinimumSize(new java.awt.Dimension(412, 130));
        Register_Confirm.setPreferredSize(new java.awt.Dimension(412, 130));

        REG_windowConfirm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        BUT_OK.setText("OK");
        BUT_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUT_OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Register_ConfirmLayout = new javax.swing.GroupLayout(Register_Confirm.getContentPane());
        Register_Confirm.getContentPane().setLayout(Register_ConfirmLayout);
        Register_ConfirmLayout.setHorizontalGroup(
            Register_ConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Register_ConfirmLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BUT_OK)
                .addGap(178, 178, 178))
            .addGroup(Register_ConfirmLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(REG_windowConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        Register_ConfirmLayout.setVerticalGroup(
            Register_ConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Register_ConfirmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(REG_windowConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BUT_OK)
                .addContainerGap())
        );

        FRA_Admin.setMinimumSize(new java.awt.Dimension(400, 300));
        FRA_Admin.setResizable(false);

        jLabel12.setText("Administration Panel");

        javax.swing.GroupLayout FRA_AdminLayout = new javax.swing.GroupLayout(FRA_Admin.getContentPane());
        FRA_Admin.getContentPane().setLayout(FRA_AdminLayout);
        FRA_AdminLayout.setHorizontalGroup(
            FRA_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FRA_AdminLayout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(142, 142, 142))
        );
        FRA_AdminLayout.setVerticalGroup(
            FRA_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FRA_AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
        );

        FRA_PriceWindow.setAlwaysOnTop(true);
        FRA_PriceWindow.setMaximumSize(new java.awt.Dimension(400, 180));
        FRA_PriceWindow.setMinimumSize(new java.awt.Dimension(400, 180));
        FRA_PriceWindow.setPreferredSize(new java.awt.Dimension(400, 180));
        FRA_PriceWindow.setResizable(false);

        syndromi.add(jRadioButton1);
        jRadioButton1.setText("Ετήσια Συνδρομή");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        syndromi.add(jRadioButton2);
        jRadioButton2.setText("Εξαμηνιαία Συνδρομή");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        syndromi.add(jRadioButton3);
        jRadioButton3.setText("Μηνιαία Συνδρομή");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel8.setText("200€");

        jLabel9.setText("140€");

        jLabel10.setText("25€");

        SP_Total.setValue(1);
        SP_Total.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SP_TotalStateChanged(evt);
            }
        });

        LB_Time.setText("Σύνολο");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Συνολικό Κόστος:");

        LB_TotalPrice.setText("0,0€");

        BUT_Pay.setText("Πληρωμή");
        BUT_Pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUT_PayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FRA_PriceWindowLayout = new javax.swing.GroupLayout(FRA_PriceWindow.getContentPane());
        FRA_PriceWindow.getContentPane().setLayout(FRA_PriceWindowLayout);
        FRA_PriceWindowLayout.setHorizontalGroup(
            FRA_PriceWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FRA_PriceWindowLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(FRA_PriceWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addGroup(FRA_PriceWindowLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(LB_Time)))
                .addGap(32, 32, 32)
                .addGroup(FRA_PriceWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FRA_PriceWindowLayout.createSequentialGroup()
                        .addGroup(FRA_PriceWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FRA_PriceWindowLayout.createSequentialGroup()
                                .addComponent(SP_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(BUT_Pay))
                            .addComponent(jLabel10)
                            .addGroup(FRA_PriceWindowLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel11)))
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(FRA_PriceWindowLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LB_TotalPrice)
                        .addGap(78, 78, 78))))
        );
        FRA_PriceWindowLayout.setVerticalGroup(
            FRA_PriceWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FRA_PriceWindowLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(FRA_PriceWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FRA_PriceWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel9)
                    .addComponent(LB_TotalPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FRA_PriceWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FRA_PriceWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SP_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_Time)
                    .addComponent(BUT_Pay))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FRA_Pay.setAlwaysOnTop(true);
        FRA_Pay.setMinimumSize(new java.awt.Dimension(408, 480));
        FRA_Pay.setPreferredSize(new java.awt.Dimension(408, 480));
        FRA_Pay.setResizable(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Secure Payment Info");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymsym/lib/card-icons.png"))); // NOI18N

        jLabel15.setText("Όνομα (όπως εμφανίζεται στη κάρτα)");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Αριθμός Κάρτας (χωρίς παύλες ή κενά)");

        jLabel17.setText("Ημερομηνία λήξης");

        jLabel18.setText("CVV");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymsym/lib/cvv-graphic.png"))); // NOI18N
        jLabel19.setText("jLabel19");

        jRadioButton4.setText("Έχω διαβάσει και αποδέχομαι τους όρους χρήσης.");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        BUT_FullBuy.setText("Ολοκλήρωση πληρωμής");
        BUT_FullBuy.setEnabled(false);
        BUT_FullBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUT_FullBuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FRA_PayLayout = new javax.swing.GroupLayout(FRA_Pay.getContentPane());
        FRA_Pay.getContentPane().setLayout(FRA_PayLayout);
        FRA_PayLayout.setHorizontalGroup(
            FRA_PayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(FRA_PayLayout.createSequentialGroup()
                .addGroup(FRA_PayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FRA_PayLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel13))
                    .addGroup(FRA_PayLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(FRA_PayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FRA_PayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel17)
                                .addComponent(jLabel15)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addComponent(jTextField2))
                            .addGroup(FRA_PayLayout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FRA_PayLayout.createSequentialGroup()
                                .addGroup(FRA_PayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19))
                            .addComponent(jRadioButton4))))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FRA_PayLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FRA_PayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FRA_PayLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FRA_PayLayout.createSequentialGroup()
                        .addComponent(BUT_FullBuy)
                        .addGap(183, 183, 183))))
        );
        FRA_PayLayout.setVerticalGroup(
            FRA_PayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FRA_PayLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(FRA_PayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FRA_PayLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FRA_PayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addGap(18, 18, 18)
                .addComponent(BUT_FullBuy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBox1.addItem("01 - January");
        jComboBox1.addItem("01 - February");
        jComboBox1.addItem("01 - March");
        jComboBox1.addItem("01 - April");
        jComboBox1.addItem("01 - May");
        jComboBox1.addItem("01 - June");
        jComboBox1.addItem("01 - July");
        jComboBox1.addItem("01 - August");
        jComboBox1.addItem("01 - September");
        jComboBox1.addItem("01 - October");
        jComboBox1.addItem("01 - November");
        jComboBox1.addItem("01 - December");
        jComboBox2.addItem("2018");jComboBox2.addItem("2019");
        jComboBox2.addItem("2020");jComboBox2.addItem("2021");
        jComboBox2.addItem("2022");jComboBox2.addItem("2023");
        jComboBox2.addItem("2024");jComboBox2.addItem("2025");
        jComboBox2.addItem("2026");jComboBox2.addItem("2027");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(513, 260));

        GymSum.setText("GymSym");

        Username.setText("Username:");

        Password.setText("Password:");

        BUT_Login.setText("Log In");
        BUT_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUT_LoginActionPerformed(evt);
            }
        });

        BUT_Cancel.setText("Cancel");
        BUT_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUT_CancelActionPerformed(evt);
            }
        });

        BUT_FPass.setText("Forgot Password");

        BUT_Register.setText("Register");
        BUT_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUT_RegisterActionPerformed(evt);
            }
        });

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BUT_Login)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Username, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Password))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TF_Username)
                                .addComponent(BUT_Cancel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BUT_FPass, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                        .addComponent(LB_Message, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(GymSum)
                        .addGap(90, 90, 90)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(BUT_Register)
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GymSum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username)
                    .addComponent(TF_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BUT_FPass)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BUT_Login)
                    .addComponent(BUT_Cancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_Message, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUT_Register))
                .addGap(116, 116, 116))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        
        p1.setEchoChar('&');
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void BUT_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUT_CancelActionPerformed
            try {
                fw.close();
            } catch (IOException ex) {
                Logger.getLogger(GymFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        System.exit(0);
    }//GEN-LAST:event_BUT_CancelActionPerformed

    private void BUT_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUT_RegisterActionPerformed
        jFrame_Register.setVisible(true);
        jFrame_Register.setLocationRelativeTo(null);
    }//GEN-LAST:event_BUT_RegisterActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jFrame_Register.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void REG_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REG_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REG_EmailActionPerformed

    private void REG_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REG_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REG_NameActionPerformed

    private void BUT_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUT_LoginActionPerformed
        char[] pass1 = jPasswordField1.getPassword();
        char[] adminpass = {'a','d','m','i','n'};
        
        if(TF_Username.getText().length()<1){
            
            LB_Message.setText("Please type in your username.");
            return;
            
        }
        
        if(Arrays.equals(pass1, adminpass) && TF_Username.getText().equals("Admin")){

            LB_Message.setText("Administration Login successful.");
            FRA_Admin.setVisible(true);
            FRA_Admin.setLocationRelativeTo(null);
            return;
        }
        
            
        int line_countU = 5;
        int line_countP = 6;
        boolean found = false;
            try {
                String reg_amU = Files.readAllLines(Paths.get("dat.ass")).get(line_countU);
                String reg_amP = Files.readAllLines(Paths.get("dat.ass")).get(line_countP);
                char[] comp_pass = reg_amP.toCharArray();
                
                do{
                    
                    try{
                        if(reg_amU.equalsIgnoreCase(TF_Username.getText())){
                            found = true;
                            
                            if(Arrays.equals(comp_pass, pass1)){
                                
                                LB_Message.setText("Successful Logged In.");
                                
                            } else {
                                line_countP += 8;
                            }

                        } else {
                            line_countU += 8;
                        }
                    
                    }catch (Exception e1){
                        LB_Message.setText("There is user with that Username.");
                        break;
                    }    
                        
                }while(!found);
                
                
            } catch (IOException ex) {
                Logger.getLogger(GymFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_BUT_LoginActionPerformed

    private void BUT_RegConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUT_RegConfirmActionPerformed
        Registration_Message.setText("");
        Scanner sc1 = new Scanner("dat.ass");
        if(REG_Name.getText().length()<1 || REG_Surname.getText().length()<1 || REG_Username.getText().length()<1 || REG_Password.getText().length()<1 || REG_Email.getText().length()<1){
            Registration_Message.setForeground(Color.red);
            Registration_Message.setText("Please fill in all the fields.");
            return;
        } else if(!Arrays.equals(REG_Password.getPassword(), REG_ConfirmPass.getPassword())){
            Registration_Message.setForeground(Color.red);
            Registration_Message.setText("Passwords are different.");
            return;
        }
        
        try{
           
            //int reg_amInt = Integer.parseInt(reg_am);
            //reg_amInt++;
            fw.write("\n =====Customer=====" + "\n Name:\t\t" + REG_Name.getText() + "\n Surname:\t" + REG_Surname.getText() + "\n Username:\t" + REG_Username.getText() + "\n Password:\t" + REG_Password.getText() + "\n Email:\t\t" + REG_Email.getText() + "\n \n");
            jFrame_Register.setVisible(false);
            Register_Confirm.setVisible(true);
            Register_Confirm.setLocationRelativeTo(null);
            REG_windowConfirm.setText("Registration for customer " + REG_Name.getText() + " " + REG_Surname.getText() + "\n has been completed.");
            REG_Name.setText("");
            REG_Surname.setText("");
            REG_Username.setText("");
            REG_Password.setText("");
            REG_ConfirmPass.setText("");
            REG_Email.setText("");
            
        }catch(IOException e1){
            
        }
    }//GEN-LAST:event_BUT_RegConfirmActionPerformed

    private void BUT_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUT_OKActionPerformed
        Register_Confirm.setVisible(false);
    }//GEN-LAST:event_BUT_OKActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        LB_Time.setText("Χρόνια:");
        base_price = 200.0;
        price = base_price * Integer.parseInt(SP_Total.getValue().toString());
        LB_TotalPrice.setText(price + "€");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void BUT_PriceWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUT_PriceWindowActionPerformed
        FRA_PriceWindow.setVisible(true);
        FRA_PriceWindow.setLocationRelativeTo(null);
    }//GEN-LAST:event_BUT_PriceWindowActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        LB_Time.setText("Εξάμηνα:");
        base_price = 140.0;
        price = base_price * Integer.parseInt(SP_Total.getValue().toString());
        LB_TotalPrice.setText(price + "€");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        LB_Time.setText("Μήνες:");
        base_price = 25.0;
        price = base_price * Integer.parseInt(SP_Total.getValue().toString());
        LB_TotalPrice.setText(price + "€");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void SP_TotalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SP_TotalStateChanged
        price = base_price * Integer.parseInt(SP_Total.getValue().toString());
        LB_TotalPrice.setText(price + "€");
    }//GEN-LAST:event_SP_TotalStateChanged

    private void BUT_PayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUT_PayActionPerformed
        FRA_Pay.setVisible(true);
        FRA_Pay.setLocationRelativeTo(null);
        //CardsIcon.setIcon(new ImageIcon(scaleImage));
    }//GEN-LAST:event_BUT_PayActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        BUT_FullBuy.setEnabled(true);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void BUT_FullBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUT_FullBuyActionPerformed
        FRA_Pay.setVisible(false);
        Register_Confirm.setLocationRelativeTo(null);
        REG_windowConfirm.setText("Η συναλλαγή ολοκληρώθηκε.");
        Register_Confirm.setVisible(true);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
    }//GEN-LAST:event_BUT_FullBuyActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GymFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GymFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GymFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GymFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                GymFrame ass1 = new GymFrame();
                ass1.setVisible(true);
                ass1.setLocationRelativeTo(null);
                    try{
                        
                        fw = new FileWriter("dat" + ".ass");
                        //fw.write("Registrations: \n" + "0");
                        //fw.close();
                        
                    } catch(IOException e1){
                        
                        
                    }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUT_Cancel;
    private javax.swing.JButton BUT_FPass;
    private javax.swing.JButton BUT_FullBuy;
    private javax.swing.JButton BUT_Login;
    private javax.swing.JButton BUT_OK;
    private javax.swing.JButton BUT_Pay;
    private javax.swing.JButton BUT_PriceWindow;
    private javax.swing.JButton BUT_RegConfirm;
    private javax.swing.JButton BUT_Register;
    private javax.swing.JFrame FRA_Admin;
    private javax.swing.JFrame FRA_Pay;
    private javax.swing.JFrame FRA_PriceWindow;
    private javax.swing.JLabel GymSum;
    private javax.swing.JLabel LB_Message;
    private javax.swing.JLabel LB_Time;
    private javax.swing.JLabel LB_TotalPrice;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField REG_ConfirmPass;
    private javax.swing.JTextField REG_Email;
    private javax.swing.JTextField REG_Name;
    private javax.swing.JPasswordField REG_Password;
    private javax.swing.JTextField REG_Surname;
    private javax.swing.JTextField REG_Username;
    private javax.swing.JLabel REG_windowConfirm;
    private javax.swing.JDialog Register_Confirm;
    private javax.swing.JLabel Registration_Message;
    private javax.swing.JSpinner SP_Total;
    private javax.swing.JTextField TF_Username;
    private javax.swing.JLabel Username;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFrame jFrame_Register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.ButtonGroup syndromi;
    // End of variables declaration//GEN-END:variables
}
